# -*- coding: utf-8 -*-
"""Women's 2025 ODI WC Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16u_7C665o9X13KHP5LtwSkKRcCP5uTTv
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_batting = pd.read_csv('/content/batting_stats.csv')
df_bowling = pd.read_csv('/content/bowling_stats.csv')
df_match = pd.read_csv('/content/match_records.csv')

df_batting

# Names of the columns start from uppercase we convert this into the lower case

df_batting.columns = df_batting.columns.str.lower()

df_batting

df_batting.info()

df_batting.describe()

df_batting.isna().sum()

df_bowling

# Here also the columns name start from upper case we have to convert this into the lower case

df_bowling.columns = df_bowling.columns.str.lower()

df_bowling

# We create seperates column for the highest wickets from the BBI

df_bowling['highest_wickets'] = df_bowling['bbi'].str.split('--').str[0]

df_bowling

df_bowling.info()

# Convert the data type of the Highest_wickets object into the int

df_bowling['highest_wickets'] = df_bowling['highest_wickets'].astype(int)

df_bowling.info()

df_bowling.describe()

df_bowling.isna().sum()

df_match

df_match.columns

df_match.info()

df_match.isna().sum()

# In the match file there are some null value we remove this null value and fill according to their data type

df_match = df_match.fillna({
    'toss_winner': 'No result',
    'toss_decision': 'No result',
    'winning_team': 'No result',
    '1st_score': 0.0,
    '1st_wkts': 0.0,
    '2nd_score': 0.0,
    '2nd_wkts': 0.0,
    'DLS_involved': 'No result',
    'wb_runs': 0.0,
    'wb_wickets': 0.0,
    'POTM': 'No result',
    'top_scorer': 'No result',
    'highscore': 0.0,
    'best_bowling': 'No result',
    'best_bowling_figure': 'No Result'
})

# By mistake we replace the bowling figure by no result we have to replace it by bowling figure

df_match['best_bowling_figure'] = df_match['best_bowling_figure'].replace('No result','0--0')

df_match

df_match.isna().sum()

#  Which team played the highest number of matches?

highest_match_played = pd.concat([df_match['team1'],df_match['team2']]).value_counts()

plt.bar(highest_match_played.index,highest_match_played,color = 'blue',edgecolor = 'black')
plt.title('Team Matches',fontweight = 'bold')
plt.xlabel('Team')
plt.xticks(rotation = 90)
plt.ylabel('Matches')
for i , v in enumerate(highest_match_played.values):
  plt.text(i,v+0.1,str(v),ha = 'center')

plt.show()

# Which team won the most matches in the tournament?

most_win = df_match['winning_team'].value_counts()

plt.bar(most_win.index,most_win.values,color = 'Teal',edgecolor = 'black')
plt.title('Most Win')
plt.xlabel('Team')
plt.ylabel('Wins')
plt.xticks(rotation = 80)

plt.show()

# Which venue hosted the maximum matches?

max_venue = df_match['venue_stadium'].value_counts()
plt.bar(max_venue.index,max_venue.values,color = '#1B65A7',edgecolor = 'black')
plt.title('Venue vs Number of matches played')
plt.xlabel('Venue')
plt.xticks(rotation = 80)
plt.ylabel('Number of matchs')

plt.show()

# What are the total runs scored by each team across the entire tournament?
df_score = df_match.melt(
    id_vars=['team1', 'team2'],
    value_vars=['1st_score', '2nd_score'],
    var_name='Innings',
    value_name='Runs'
)
df_score['Team'] = df_score.apply(
    lambda row:
        row['team1'] if row['Innings'] == '1st_score' else row['team2'],
    axis=1
)
total_runs = df_score.groupby('Team')['Runs'].sum().reset_index()
total_runs.sort_values(by='Runs', ascending=False, inplace=True)


plt.bar(total_runs['Team'],total_runs['Runs'],edgecolor = 'black')
plt.title('Total run scored by each team')
plt.xlabel('Teams')
plt.xticks(rotation = 70)
plt.ylabel('Runs')

for i , v in enumerate(total_runs['Runs']):
  plt.text(i,v+30,str(v),ha = 'center')

plt.show()

# Which match had the highest total runs scored?


df_match['match_between'] = df_match['team1'] +' vs '+ df_match['team2']
df_match['match_total'] = df_match['1st_score'] + df_match['2nd_score']

highest_match_total = df_match[['match_between','match_total']].sort_values('match_total',ascending = False).head(7)



plt.bar(highest_match_total['match_between'],highest_match_total['match_total'])
plt.title('Highest match total')
plt.xlabel('Matche Between')
plt.xticks(rotation = 90)
plt.ylabel('Runs')

for i , v in enumerate(highest_match_total['match_total']):
  plt.text(i,v+5,str(v),ha = 'center')

plt.show()

# Who are the top 10 “Player of the Match” award winners?

player_of_the_match = df_match['POTM'].value_counts().head(10)
player_of_the_match

# Which team has the highest average score per match?

highest_avg_per_match = df_score.groupby('Team')['Runs'].mean().sort_values(ascending = False).round(2)
plt.bar(highest_avg_per_match.index,highest_avg_per_match.values,edgecolor = 'black')
plt.title('Highest average score per match')
plt.xlabel('Team')
plt.xticks(rotation = 90)
plt.ylabel('Runs')
for i , v in enumerate(highest_avg_per_match.values):
  plt.text(i,v+2,str(v),ha = 'center')
plt.show()

# Which team has the lowest average score per match?

lowest_avg_per_match = df_score.groupby('Team')['Runs'].mean().sort_values(ascending = True).round(2)
plt.bar(lowest_avg_per_match.index,lowest_avg_per_match.values,edgecolor = 'black')
plt.title('Lowest average score per match')
plt.xlabel('Team')
plt.xticks(rotation = 90)
plt.ylabel('Runs')
for i , v in enumerate(lowest_avg_per_match.values):
  plt.text(i,v+2,str(v),ha = 'center')
plt.show()

# What is the frequency of wins by runs vs wins by wickets?


df_match['Result_Type'] = df_match.apply(
    lambda row: 'Runs' if row['wb_runs'] > 0
    else ('Wickets' if row['wb_wickets'] > 0 else 'No Result'),
    axis=1
)

freq_wins = df_match['Result_Type'].value_counts()
freq_wins
plt.bar(freq_wins.index,freq_wins.values,edgecolor = 'black')
plt.title('Frequency of wins by runs vs wickets')
plt.xlabel('Win by ')
plt.ylabel('Winning counts')


plt.show()

# Which match had the closest winning margin?

closest_win_margin = df_match[df_match['wb_runs'] > 0][['match_between','wb_runs']].sort_values('wb_runs').reset_index(drop=True)

plt.bar(closest_win_margin['match_between'],closest_win_margin['wb_runs'],edgecolor = 'black')
plt.title('Closest win margin')
plt.xlabel('Match Between')
plt.xticks(rotation = 90)
plt.ylabel('Margin')
for i , v in enumerate(closest_win_margin['wb_runs']):
  plt.text(i,v+2,str(v),ha = 'center')
plt.show()

# Which match had the biggest winning margin?

biggest_win_margin = df_match[df_match['wb_runs'] > 0][['match_between','wb_runs']].sort_values('wb_runs',ascending = False).reset_index(drop=True)

plt.bar(biggest_win_margin['match_between'],biggest_win_margin['wb_runs'],edgecolor = 'black')
plt.title('Biggest win margin')
plt.xlabel('Match Between')
plt.xticks(rotation = 90)
plt.ylabel('Margin')
for i , v in enumerate(biggest_win_margin['wb_runs']):
  plt.text(i,v+2,str(v),ha = 'center')
plt.show()

# Which venue had the highest average match score?

highest_avg_venue_score = df_match.groupby('venue_stadium')['match_total'].mean().round(2)

plt.bar(highest_avg_venue_score.index,highest_avg_venue_score.values,edgecolor = 'black')
plt.title('Highest average match score by venue')
plt.xlabel('Venue')
plt.xticks(rotation = 90)
plt.ylabel('Average Score')
for i , v in enumerate(highest_avg_venue_score.values):
  plt.text(i,v+2,str(v),ha = 'center')
plt.show()

# How many matches did each team win while chasing?

win_chasing = df_match['Result_Type'].value_counts()
win_chasing

# Which team pair played each other the most?
df_match['Team_Pair'] = df_match.apply(
    lambda x: ' vs '.join(sorted([x['team1'], x['team2']])), axis=1
)
team_pair = df_match['Team_Pair'].value_counts()
team_pair

# Which team has the highest average winning margin?

highest_winning_margin = df_match.groupby('winning_team')['wb_runs'].mean().sort_values(ascending = False).round(2)

plt.bar(highest_winning_margin.index,highest_winning_margin.values,edgecolor = 'black')
plt.title('Highest average winning margin')
plt.xlabel('Winning Team')
plt.xticks(rotation = 90)
plt.ylabel('Winning Margin')
for i , v in enumerate(highest_winning_margin.values):
  plt.text(i,v+1,str(v),ha = 'center')
plt.show()

# How does total match score change over time?

df_match['date'] = pd.to_datetime(df_match['date'])

score_change = df_match.groupby('date')['match_total'].sum()

plt.plot(score_change.index,score_change.values,marker = 'o')
plt.title('Total Match Score Over Time')
plt.xlabel('Date')
plt.ylabel('Total Score')
plt.xticks(rotation = 90)

plt.tight_layout()
plt.show()

# What is the average first-innings score for each team?

avg_first_innings_score = df_match.groupby('team1')['1st_score'].mean().round(2)

plt.bar(avg_first_innings_score.index,avg_first_innings_score.values,edgecolor = 'black')
plt.title('Average First Innings Score')
plt.xlabel('Team')
plt.xticks(rotation = 90)
plt.ylabel
for i , v in enumerate(avg_first_innings_score.values):
  plt.text(i,v+5,str(v),ha = 'center')
plt.show()

# What is the average second-innings score for each team?

avg_second_innings_score = df_match.groupby('team1')['2nd_score'].mean().round(2)
plt.bar(avg_second_innings_score.index,avg_second_innings_score.values,edgecolor = 'black')
plt.title('Average Second Innings Score')
plt.xlabel('Team')
plt.xticks(rotation = 90)
for i , v in enumerate(avg_second_innings_score.values):
  plt.text(i,v+1,str(v),ha = 'center')
plt.show()

# Which team conceded the most runs?


df_match[['team1', 'team2','toss_winner', 'toss_decision','1st_score','2nd_score']]

team1 = df_match[['team1','2nd_score']]
team2 = df_match[['team2','1st_score']]

team1_df = team1.reset_index().rename(columns={'team1': 'Team', '2nd_score': 'Score'})
team2_df = team2.reset_index().rename(columns={'team2': 'Team', '1st_score': 'Score'})
team1_df
combined_df = pd.concat([team1_df, team2_df], ignore_index=True)
combined_df
conceded_most_runs = combined_df.groupby('Team')['Score'].sum().sort_values(ascending = False)

plt.bar(conceded_most_runs.index,conceded_most_runs.values,color = 'Teal',edgecolor = 'black')
plt.title('Most runs conceded')
plt.xlabel('Team')
plt.xticks(rotation = 90)
plt.ylabel('Runs')

for i , v in enumerate(conceded_most_runs.values):
  plt.text(i,v+30,str(v),ha = 'center')
plt.show()

# Which team conceded the least runs?


conceded_least_runs = combined_df.groupby('Team')['Score'].sum().sort_values()

plt.bar(conceded_least_runs.index,conceded_least_runs.values,color = 'Teal',edgecolor = 'black')
plt.title('Least runs conceded')
plt.xlabel('Team')
plt.xticks(rotation = 80)
plt.ylabel('Runs')

for i , v in enumerate(conceded_least_runs.values):
  plt.text(i,v+30,str(v),ha = 'center')

plt.show()

# Which venue hosted matches with the highest number of close finishes?

closest_win_margin = df_match[df_match['wb_runs']>0][['venue_stadium','wb_runs']].sort_values('wb_runs').reset_index(drop=True)
closest_win_margin

# In which venue the score is 250+

df1 = df_match[['venue_stadium','1st_score']].rename(columns={'1st_score':'Score'})
df2 = df_match[['venue_stadium','2nd_score']].rename(columns={'2nd_score':'Score'})

df_new = pd.concat([df1, df2]).reset_index(drop=True)

most_times = df_new[df_new['Score']>250].value_counts().groupby('venue_stadium').size()

plt.bar(most_times.index,most_times.values,color = 'Teal',edgecolor = 'black')
plt.title('Most 250+ score ')
plt.xlabel('Venue')
plt.xticks(rotation = 90)
plt.ylabel('Matches')

for i , v in enumerate(most_times.values):
  plt.text(i,v+0.06,str(v),ha = 'center')

plt.show()